spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: doctors-service

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
minio:
  url: http://minio:9000
  access-key: maxvpire
  secret-key: max26156
  bucket:
   name: doctors