spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: appointments-service
  kafka:
      bootstrap-servers: kafka:29092
      consumer:
        group-id: appointments-consumer
