spring:
  application:
    name: rates-service
  config:
    import: optional:configserver:http://config-server:8888
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: my-consumer-group