spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: payment-service

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: payment-consumer-group


minio:
  url: http://minio:9000
  access-key: maxvpire
  secret-key: max26156
  bucket:
    name: receipts

