spring:
  application:
    name: users-service

  config:
    import: optional:configserver:http://config-server:8888

  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: doctors-consumer